name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy AZURA 45
        run: firebase deploy --only hosting:azura45 --token "$FIREBASE_TOKEN" --project azura45-pointage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy AZURA 46
        run: firebase deploy --only hosting:azura46 --token "$FIREBASE_TOKEN" --project azura46-pointage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
