name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          run: firebase deploy --only hosting --site azura45-pointage --token "$FIREBASE_TOKEN"